//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WatcherXP.rc
//
#define IDR_MANIFEST                    1
#define VS_VERSION_INFO                 1
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define ID_FILE_BTN                     101
#define IDD_WATCHERXP_DIALOG            102
#define IDS_WATCHER_EN                  102
#define ID_VIEW_BTN                     102
#define IDS_WATCHER_AR                  103
#define ID_REPORT_BTN                   103
#define IDS_OPTIONS_EN                  104
#define ID_HELP_BTN                     104
#define IDS_OPTIONS_AR                  105
#define ID_MAXBTN                       105
#define IDS_FOLDERS_EN                  106
#define ID_MIN_BTN                      106
#define IDS_FOLDERS_AR                  107
#define ID_EXITBTN                      107
#define IDS_AUTOSTART_EN                108
#define ID_TIMER1                       108
#define ID_START_BTN                    108
#define IDS_AUTOSTART_AR                109
#define IDM_ABOUTBOX                    109
#define ID_STOP_BTN                     109
#define IDS_STARTUP_EN                  110
#define ID_HIDE_BTN                     110
#define IDS_STARTUP_AR                  111
#define ID_KB_BTN                       111
#define IDS_HIDE_EN                     112
#define ID_WT_BTN                       112
#define IDS_HIDE_AR                     113
#define ID_IE_BTN                       113
#define IDS_PASS_EN                     114
#define ID_FF_BTN                       114
#define IDS_PASS_AR                     115
#define ID_SS_BTN                       115
#define IDS_ENTERPASS_EN                116
#define ID_U_HELP_BTN                   116
#define IDS_ENTERPASS_AR                117
#define ID_ABOUT_BTN                    117
#define IDS_CONFIRM_EN                  118
#define ID_U_EXIT_BTN                   118
#define IDS_CONFIRM_AR                  119
#define ID_OPTIONS_BTN                  119
#define IDS_WATCH_EN                    120
#define ID_IDL_BTN                      120
#define IDS_WATCHWHAT_AR                121
#define ID_NEXT_BTN                     121
#define IDS_KEY_EN                      122
#define ID_PREV_BTN                     122
#define IDS_KEY_AR                      123
#define ID_STOP                         123
#define IDS_WA_EN                       124
#define ID_REFRESH_BTN                  124
#define IDS_WA_AR                       125
#define ID_HOME_BTN                     125
#define IDS_WT_EN                       126
#define ID_EXIT_BTN                     126
#define IDS_WT_AR                       127
#define ID_MAX_BTN                      127
#define IDR_MAINFRAME                   128
#define IDS_FF_EN                       128
#define ID_N_STOP_BTN                   128
#define IDI_NEXT                        129
#define IDS_FF_AR                       129
#define ID_FILE_START                   130
#define IDI_PREV                        130
#define IDS_SS_EN                       130
#define IDB_MENU_NORMAL                 130
#define ID_FILE_STOP                    131
#define IDI_STOP                        131
#define IDS_SS_AR                       131
#define IDB_MENU_OVER                   131
#define ID_FILE_EXIT                    132
#define IDI_REFRESH                     132
#define IDS_SECOND_EN                   132
#define IDB_SYS_MENU_NORMAL             132
#define ID_VIEW_KEYSTROKES              133
#define IDI_HOME                        133
#define IDS_SECOND_AR                   133
#define IDB_SYS_MENU_OVER               133
#define ID_VIEW_WEBADDRESSES            134
#define IDI_GO                          134
#define IDS_CHOOSEFOLDER_EN             134
#define IDB_COM_BTN                     134
#define ID_VIEW_WINDOWTITLES            135
#define IDS_CHOOSEFOLDER_AR             135
#define IDB_COM_OVER_BTN                135
#define ID_VIEW_FILEFOLDERCHANGES       136
#define IDS_ADD2LIST_EN                 136
#define IDB_EXBTN                       136
#define ID_VIEW_SCREENSHOTS             137
#define IDS_ADD2LIST_AR                 137
#define IDB_EXBTN_OVER                  137
#define ID_REPORT_KEYSTROKES            138
#define IDS_REMOVE_EN                   138
#define ID_REPORT_W                     139
#define IDS_REMOVE_AR                   139
#define IDB_HEAD_IDL_BTN                139
#define ID_REPORT_WINDOWTITLES          140
#define IDS_OK_EN                       140
#define ID_REPORT_FILEFOLDERCHANGES     141
#define IDS_OK_AR                       141
#define IDB_REFRESH_U                   141
#define IDS_CANCEL_EN                   142
#define IDB_STOP_U                      142
#define ID_HELP_TOPICS                  143
#define IDS_CANCEL_AR                   143
#define IDB_PREV_U                      143
#define ID_HELP_ABOUT                   144
#define IDB_NEXT_U                      144
#define ID_FILE_BEINVISIBLE             145
#define IDB_HOME_U                      145
#define ID_VIEW_OPTIONS                 146
#define IDB_HOME_O                      146
#define IDB_NEXT_O                      147
#define IDD_OPTIONS                     148
#define IDB_PREV_O                      148
#define IDB_STOP_O                      149
#define IDD_FOLDERS                     150
#define IDB_BITMAP1                     150
#define IDB_REFRESH_O                   150
#define IDD_VIEWER                      152
#define IDD_PASSWORD                    153
#define ID_REPORT_CLEARDATA             155
#define IDS_STRING172                   172
#define ID_UILANGUAGE_ARABIC            173
#define ID_UILANGUAGE_ENGLISH           174
#define IDC_CHECK1                      1000
#define IDC_CHECK2                      1001
#define IDC_CHECK3                      1002
#define IDC_EDIT1                       1003
#define IDC_EDIT2                       1004
#define IDC_BUTTON1                     1005
#define IDC_CHECK11                     1005
#define IDC_CHECK6                      1006
#define IDC_BUTTON2                     1006
#define IDC_CHECK7                      1007
#define IDC_LIST1                       1007
#define IDC_BUTTON4                     1007
#define IDC_CHECK8                      1008
#define IDC_BUTTON3                     1008
#define IDC_BUTTON5                     1008
#define IDC_CHECK9                      1009
#define IDC_BUTTON6                     1009
#define IDC_CHECK10                     1010
#define IDC_BUTTON7                     1010
#define IDC_BUTTON8                     1011
#define IDC_EXPLORER1                   1014
#define IDC_COMBO1                      1015
#define IDC_EDIT3                       1016
#define IDC_GO                          1017
#define IDC_STOP                        1018
#define IDC_REFRESH                     1019
#define IDC_PREV                        1020
#define IDC_NEXT                        1021
#define IDC_PREV2                       1022
#define IDC_STATIC_ENTER                1022
#define IDC_STATIC_CONFIRM              1023
#define IDC_STATIC_WATCH                1024
#define IDC_STATIC_SECOND               1025
#define IDC_STATIC_VERSION              1026
#define IDC_STATIC_ABOUT                1027
#define IDC_STATIC_INTERVAL             1028
#define IDC_CHOOSE_FOLDERS              1029
#define IDC_STATIC_HOT                  1030
#define IDC_HOT                         1031
#define IDS_OPTIONS_HOTKEY              2043
#define IDS_FILE_UIEN                   3402
#define IDS_VIEW_WT                     3405
#define IDS_VIEW_IE                     3406
#define IDS_BTN_FILE                    20001
#define IDS_BTN_VIEW                    20002
#define IDS_BTN_REPORT                  20003
#define IDS_BTN_HELP                    20004
#define IDS_FILE_START                  20005
#define IDS_FILE_STOP                   20006
#define IDS_FILE_HIDE                   20007
#define IDS_FILE_UILANG                 20008
#define IDS_FILE_UIAR                   20009
#define IDS_STRING20010                 20010
#define IDS_REPORT_CLEAR                20010
#define IDS_FILE_EXIT                   20011
#define IDS_VIEW_KEY                    20012
#define IDS_VIEW_KB                     20012
#define IDS_VIEW_FF                     20015
#define IDS_VIEW_SS                     20016
#define IDS_VIEW_OPTIONS                20017
#define IDS_HELP_ABOUT                  20018
#define IDS_HELP_TOPICS                 20019
#define IDS_MSG_KB                      20020
#define IDS_MSG_IE                      20021
#define IDS_MSG_WT                      20022
#define IDS_MSG_FF                      20023
#define IDS_MSG_REG                     20024
#define IDS_VIEWER_NOIMAGE              20025
#define IDS_VIEWER_WT                   20026
#define IDS_VIEWER_PAUSE                20027
#define IDS_VIEWER_STOP                 20028
#define IDS_VIEWER_NEXT                 20029
#define IDS_VIEWER_PREV                 20030
#define IDS_VIEWER_INTERVAL             20031
#define IDS_VIEWER_MAXSPEED             20032
#define IDS_VIEWER_100MILLIS            20033
#define IDS_VIEWER_500MILLIS            20034
#define IDS_OPTIONS_AUTOSTART           20035
#define IDS_OPTIONS_STARTUP             20036
#define IDS_OPTIONS_AUTOHIDE            20037
#define IDS_OPTIONS_PASS                20038
#define IDS_OPTIONS_ENTERPASS           20039
#define IDS_OPTIONS_CONFIRM             20040
#define IDS_OPTIONS_WHAT                20042
#define IDS_OPTIONS_KB                  20044
#define IDS_OPTIONS_IE                  20045
#define IDS_OPTIONS_WT                  20046
#define IDS_OPTIONS_FF                  20047
#define IDS_OPTIONS_SS                  20048
#define IDS_OPTIONS_OK                  20049
#define IDS_OPTIONS_CHOOSEF             20050
#define IDS_OPTIONS_CANCEL              20051
#define IDS_OPTIONS_SECOND              20052
#define IDS_OPTIONS_REPASS              20053
#define IDS_FOLDERLIST_WT               20054
#define IDS_FOLDERLIST_CHOOSE           20055
#define IDS_FOLDERLIST_ADD              20056
#define IDS_FOLDERLIST_DEL              20057
#define IDS_ABOUT_VER                   20058
#define IDS_ABOUT_ME                    20059

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           129
#endif
#endif
